#image: java:8-jdk-alpine
image: java:8
pipelines:
  default:
  - step:
      script:
      - bash ./gradlew build
      - ls -lR
      - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"build/libs/devoxx-talks-0.0.1-SNAPSHOT.jar"
